hw10/hw10/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw10/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('author/<str:fullname>',views.author_about,name='author_about'),
    path('new_author/', views.new_author, name='new_author'),
    path('new_quote/', views.new_quote, name='new_quote'),
    path('tag/<str:name>/', views.tag_info, name='tag_info'),
    path('tag/<str:name>/<int:page>/', views.tag_info, name='tag_paginate'),
    path('get_data/', views.get_data, name='get_data'),
]

hw10/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:pk>/edit/', views.edit_quote, name='edit_quote'),
    path('profile/<int:pk>/delete/', views.delete_quote, name='delete_quote'),
]

hw10/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)
            

hw10/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile

from quotes.models import Quote, Tag
from quotes.widgets import TagCheckboxSelectMultiple

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    
    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

class QuoteForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=TagCheckboxSelectMultiple)

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

hw10/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import RegisterForm, LoginForm, ProfileForm, QuoteForm

from quotes.models import Quote, Author, Tag

@login_required
def profile(request):
    quotes = Quote.objects.all()
    quotes_user = Quote.objects.filter(created_by=request.user)

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'users/profile.html', {'profile_form': profile_form, "quotes": quotes, "quotes_user": quotes_user})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:root')

def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:root')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def edit_quote(request, pk):
    quote = get_object_or_404(Quote, pk=pk)
    if request.method == 'POST':
        form = QuoteForm(request.POST, instance=quote)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = QuoteForm(instance=quote)
    return render(request, 'users/edit_quote.html', {'form': form})

@login_required
def delete_quote(request, pk):
    quote = get_object_or_404(Quote, pk=pk)
    if request.method == 'POST':
        quote.delete()
        messages.success(request, 'Quote deleted successfully')
        return redirect('users:profile')
    return render(request, 'users/delete_quote.html', {'quote': quote})

hw10/users/templates/users/delete_quote.html
{% extends 'quotes/base_for_forms.html' %}

{% block content %}
<h2 style="margin-left: 100px">Delete quote</h2>
<div style="margin-left: 100px"><h3>Are you sure you want to delete the quote?</h3></div>
<div style="margin-left: 100px"><em>{{ quote.quote }}</em></div>
<form method="post">
    {% csrf_token %}
    <div>
    <button type="submit" style="width: 250px;" class="btn btn-primary">Delete</button>
    <a href="{% url 'users:profile' %}" style="width: 250px;" class="btn btn-secondary">Cancel</a>
    </div>
</form>
{% endblock %}

hw10/users/templates/users/edit_quote.html
{% extends 'quotes/base_for_forms.html' %}

{% block content %}
<h2 style="margin-left: 100px">Edit quote</h2>
<form method="post">
    {% csrf_token %}
    <div><strong>Quote: </strong></div>
    <div>{{ form.quote }}</div>
    <div class="row">
        <strong>Choose tags: </strong>
        <div class="col">
            {% for tag in form.tags.field.queryset|slice:":50" %}
                <label for="tag_{{ tag.id }}"><input type="checkbox" id="tag_{{ tag.id }}" name="tags" value="{{ tag.id }}"> {{ tag.name }}</label>
            {% endfor %}
        </div>
        <div class="col">
            {% for tag in form.tags.field.queryset|slice:"50:100" %}
                <label for="tag_{{ tag.id }}"><input type="checkbox" id="tag_{{ tag.id }}" name="tags" value="{{ tag.id }}"> {{ tag.name }}</label>
            {% endfor %}
        </div>
        <div class="col">
            {% for tag in form.tags.field.queryset|slice:"100:" %}
                <label for="tag_{{ tag.id }}"><input type="checkbox" id="tag_{{ tag.id }}" name="tags" value="{{ tag.id }}"> {{ tag.name }}</label>
            {% endfor %}
        </div>


    <div>
        <strong>Author:</strong> {{ form.author }}
    </div>

    <button type="submit">Save</button>
</form>
{% endblock %}

hw10/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2 style="margin-left: 186px">Sign In</h2>
</div>

{% if messages %}
<div style="margin-left: 186px; color: red">
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

hw10/users/templates/users/profile.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h1 style="margin-left: 185px; margin-top: -100px">Profile page: {{user.username}}</h1>
    <div class="image-container" style="margin-left: 185px">
    <img src="{{ user.profile.avatar.url }}" alt="avatar of user" />
</div>
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %} style="margin-left: 100px; color:aqua">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-5">
            <div class="form-group" style="margin-left: -15px">
                <label class="small mb-1">Change Avatar:</label>
                {{ profile_form.avatar }}
                <div class="grid">
                    <button type="submit">Save Changes</button>
                    <button type="reset" class="secondary">Reset</button>
                </div>
                <span style="margin-left: 100px; color: red">{{ profile_form.errors.avatar }}</span>
            </div>
        </div>
    </div>

    <div>
        {% if messages %}
        <div>
            {% for message in messages %}
            <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %} style="color: greenyellow">
                <h3>{{ message }}</h3</div>
            {% endfor %}
        </div>
        {% endif %}

        <h2 style="margin-top:20px"><strong>Created quotes by the user: {{user.username}}</strong></h2>
        
        {% for quote in quotes_user %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{quote.quote}}</span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="{% url 'quotes:author_about' quote.author.fullname %}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag.name}}/">{{ tag.name }}</a>
            {% endfor %}
        </div>
        <a href="{% url 'users:edit_quote' quote.pk %}" style="width: 436px;" class="btn btn-primary">Edit</a>
        <a href="{% url 'users:delete_quote' quote.pk %}" style="width: 436px;" class="btn btn-secondary">Delete</a>
    </div>

{% endfor %}
    </div>
</form>

{% endblock content %}

hw10/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2 style="margin-left: 186px">Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}