hw10/hw10/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw10/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('author/<str:fullname>',views.author_about,name='author_about'),
    path('new_author/', views.new_author, name='new_author'),
    path('new_quote/', views.new_quote, name='new_quote'),
    path('tag/<str:name>/', views.tag_info, name='tag_info'),
    path('tag/<str:name>/<int:page>/', views.tag_info, name='tag_paginate'),
    path('get_data/', views.get_data, name='get_data'),
]

hw10/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:pk>/edit/', views.edit_quote, name='edit_quote'),
    path('profile/<int:pk>/delete/', views.delete_quote, name='delete_quote'),
]

hw10/quotes/models.py
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=150)
    born_date = models.CharField(max_length=150)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, default="superuser")

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=300, null=False, unique=True)
    def __str__(self):
        return self.name

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, default="superuser")
    

hw10/quotes/forms.py
from django import forms
from .models import Author, Quote, Tag
from .widgets import TagCheckboxSelectMultiple

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=TagCheckboxSelectMultiple)
    
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

class SearchForm(forms.Form):
    search_tags = forms.CharField(label='Search tags', max_length=50)

hw10/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from django.core.paginator import Paginator
from django.db.models import Count

from .utils import get_mongodb
from .models import Author, Quote, Tag
from .forms import AuthorForm, QuoteForm,SearchForm

from utils.scrape_data import run_spider
from utils.migrate_from_scrape_files import fill_database

def main(request, page=1):

    quotes = Quote.objects.all()
    form = SearchForm()
    if 'search_tags' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            search_tags = form.cleaned_data['search_tags']
            quotes = quotes.filter(tags__name__icontains=search_tags)
    
    top_ten_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/index.html", context={'quotes': quotes_on_page, 'top_ten_tags': top_ten_tags, "form": form})

def author_about(request,fullname):
    author=Author.objects.get(fullname=fullname)
    return render(request,'quotes/author_about.html', context={'author': author})

def tag_info(request, name, page=1):
    quotes = Quote.objects.filter(tags__name=name)
    form = SearchForm()
    if 'search_tags' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            search_tags = form.cleaned_data['search_tags']
            quotes = quotes.filter(tags__name__icontains=search_tags)
    
    top_ten_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    per_page = 3
    paginator2 = Paginator(list(quotes), per_page)
    quotes_on_page = paginator2.page(page)
    return render(request, "quotes/taginfo.html", context={'quotes': quotes_on_page, 'top_ten_tags': top_ten_tags})

@login_required
def new_author(request):

    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.created_by = request.user.username
            author.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/new_author.html', {'form': form})

    return render(request, 'quotes/new_author.html', context={'form': AuthorForm()})

@login_required
def new_quote(request):

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            quote.created_by = request.user.username
            quote.save()
            form.save_m2m()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/new_quote.html', {'form': form})

    return render(request, 'quotes/new_quote.html', context={'form': QuoteForm()})


def get_data(request):
    run_spider()
    fill_database()
    return redirect(to='quotes:root')

hw10/quotes/templates/quotes/author_about.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="author-about" style="margin-left: 130px; max-width: 800px">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> 
    <span class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
     {{author.description}}
    </div>
</div>
{% endblock %}

hw10/quotes/templates/quotes/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0,
        minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>web_HW_10</title>
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none; margin-left: 100px">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                        {% if user.is_authenticated %}
                        <div style="margin-top: -10px; float: right">Authenticated user - <b>{{ user.username }}</b></div>
                        <ul style="float: right">
                            {% if quotes %}
                            <li><a href="{% url 'quotes:new_author' %}" role="button">Add new author</a></li>
                            <li><a href="{% url 'quotes:new_quote' %}" role="button">Add new quote</a></li>
                            {% else %}
                            <li>...Please get main data first!</li>
                            <li>...Please get main data first!</li>
                            {% endif %}
                            <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
                            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
                        </ul>
                        {% else %}
                        <ul style="float: right">
                            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
                        </ul>
                        {% endif %}
                    </div>
                </p>
            </div>
        </div>

        {% block content %} {% endblock %}



    </div>
</body>

</html>

hw10/quotes/templates/quotes/base_for_forms.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0,
        minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>web_HW_10</title>
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none; margin-left: 100px">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                        {% if user.is_authenticated %}
                        <div style="margin-top: -10px; float: right">Authenticated user - <b>{{ user.username }}</b></div>
                        <ul style="float: right">
                            {% if request.path == '/new_author/' %}
                                <li><a href="{% url 'quotes:new_quote' %}" role="button">Add new quote</a></li>
                            {% elif request.path == '/new_quote/' %}
                                <li><a href="{% url 'quotes:new_author' %}" role="button">Add new author</a></li>
                            {% endif %}
                            <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
                            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
                        </ul>
                        {% endif %}
                </p>
            </div>
        </div>

        {% block content %} {% endblock %}



    </div>
</body>

</html>

hw10/quotes/templates/quotes/index.html
{% extends "quotes/base.html"%}
{% load decrease_px %}



{% block content %}
{% if quotes %}
<div style="margin-bottom: 30px; margin-top: -55px">
    <form method="get">
        <p style="margin-left:-130px; margin-bottom: 5px"><strong>Seaching for tags</strong></p>
        <input type="text" name="search_tags" style="width: 450px; margin-left: -130px; background-color: rgba(205, 212, 240, 0.895); border: 2px solid #000002; box-shadow: 0 0 10px #000;">
        <input type="submit" value="Search" style="margin-left: 3px; width: 100px" class="btn btn-secondary">
    </form>
</div>

<div class="row">
<div class="col-md-8" style="margin-top: -5px; margin-left: 50px">

    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{quote.quote}}</span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="{% url 'quotes:author_about' quote.author.fullname %}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag.name}}/">{{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
{% endfor %}

    <nav>
        <ul class="pager">
            
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>
            
            
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                Next <span aria-hidden="true">→</span>
                </a>
            </li>
            
        </ul>
    </nav>            
</div>

    <div class="tags-box col-md-3">

    <div><h2>Top Ten tags</h2></div>
        
        {% for tag in top_ten_tags %}
        <div class="tag-item">
            {% decreasing_font_size 35 3 forloop.counter as font_size %}
            <a class="tag" style="font-size: {{ font_size }}px" href="/tag/{{tag.name}}/">{{ tag.name }}</a>
        </div>
        {% endfor %}

    </div>
</div>
{% else %}
    <div style="text-align: center; margin-top: 50px">
        <h1>No quotes found</h1>
        <a href="{% url 'quotes:get_data' %}" class="btn btn-primary" style="width: 300px; height: 70px; font-size: 30px; text-align: center;">Scrape data</a>
    </div>
{% endif %}
{% endblock %}

hw10/quotes/templates/quotes/new_author.html
{% extends 'quotes/base_for_forms.html' %}

{% block content %}
<h2 class="for-profile" style="margin-left:100px">Add new author</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <div class="class="btn-container"">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>
{% endblock %}

hw10/quotes/templates/quotes/new_quote.html
{% extends 'quotes/base_for_forms.html' %}

{% block content %}

<h2 class="for-profile" style="margin-left: 100px">Add new quote</h2>
<form method="post">
    {% csrf_token %}
    <div><strong>Quote: </strong></div>
    <div>{{ form.quote }}</div>
    <div class="row">
        <strong>Choose tags: </strong>
        <div class="col">
            {% for tag in form.tags.field.queryset|slice:":50" %}
                <label for="tag_{{ tag.id }}"><input type="checkbox" id="tag_{{ tag.id }}" name="tags" value="{{ tag.id }}"> {{ tag.name }}</label>
            {% endfor %}
        </div>
        <div class="col">
            {% for tag in form.tags.field.queryset|slice:"50:100" %}
                <label for="tag_{{ tag.id }}"><input type="checkbox" id="tag_{{ tag.id }}" name="tags" value="{{ tag.id }}"> {{ tag.name }}</label>
            {% endfor %}
        </div>
        <div class="col">
            {% for tag in form.tags.field.queryset|slice:"100:" %}
                <label for="tag_{{ tag.id }}"><input type="checkbox" id="tag_{{ tag.id }}" name="tags" value="{{ tag.id }}"> {{ tag.name }}</label>
            {% endfor %}
        </div>


    <div>
        <strong>Author:</strong> {{ form.author }}
    </div>

    <div>
    <button type="submit" style="width: 250px;" class="btn btn-primary">Submit</button>
    <button type="reset" style="width: 250px;" class="btn btn-secondary">Reset</button>
    </div>

</form>
{% endblock %}

hw10/quotes/templates/quotes/taginfo.html
{% extends "quotes/base.html"%}
{% load decrease_px %}
{% load path_split %}

{% block content %}
<div style="margin-bottom: 30px; margin-top: -85px">
    <form method="get">
        <p style="margin-left:-130px; margin-bottom: 5px"><strong>Seaching for tags</strong></p>
        <input type="text" name="search_tags" style="width: 450px; margin-left:-130px; background-color: rgba(205, 212, 240, 0.895); border: 2px solid #000002; box-shadow: 0 0 10px #000;">
        <input type="submit" value="Search" style="margin-left: 3px; width: 100px" class="btn btn-secondary">
    </form>
</div>

<div class="row">
<div class="col-md-8" style="margin-top: -5px; margin-bottom: 50px; margin-left: 50px">

    {% path_split request.path as tag_name %}
    <div><h3>
        Viewing all quotes with tag:<a class="tag" style="font-size: 21px" href="/tag/{{ tag_name }}">{{ tag_name }}</a>
        </h3>
    </div>

    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{quote.quote}}</span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="{% url 'quotes:author_about' quote.author.fullname %}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
{% endfor %}

<nav>
    <ul class="pager">
        <li class="previous">
            <a class="{% if not quotes.has_previous %} disabled {% endif %}"
            href="{% if quotes.has_previous %} {% url 'quotes:tag_paginate' name=tag_name page=quotes.previous_page_number %} {% else %} # {% endif %}">
                <span aria-hidden="true">←</span> Previous
            </a>
        </li>
        <li class="next">
            <a class="{% if not quotes.has_next %} disabled {% endif %}"
            href="{% if quotes.has_next %} {% url 'quotes:tag_paginate' name=tag_name page=quotes.next_page_number %} {% else %} # {% endif %}">
                Next <span aria-hidden="true">→</span>
            </a>
        </li>
    </ul>
</nav>      
</div>

    <div class="tags-box col-md-3">

    <div><h2>Top Ten tags</h2></div>
        
        {% for tag in top_ten_tags %}
        <div class="tag-item">
            {% decreasing_font_size 35 3 forloop.counter as font_size %}
            <a class="tag" style="font-size: {{ font_size }}px" href="/tag/{{ tag.name }}/">{{ tag.name }}</a>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}